### ISSUE TITLE
Audio El Height Problem

### ISSUE THREAD

**Issue by aidenlx** [aidenlx/media-extended#47]
![image](https://user-images.githubusercontent.com/31102694/122504851-b55feb00-d02d-11eb-8ee9-2720a69991e5.png)

**Comment by AidenLx** [comment]
temp fix: add the following to css snippets: 
```css
div.external-video, div.local-media {
    min-height: unset !important;
    height: unset !important;
}
```
