### ISSUE TITLE
Setting Menu Get Hidden by Header

### ISSUE THREAD

**Issue by iris2jane** [aidenlx/media-extended#52]
![image](https://user-images.githubusercontent.com/36763930/126972687-42d06575-eb63-40cc-9ea7-16f409e66884.png)

**Comment by aidenlx** [comment]
This is an issue related to [plyr](https://github.com/sampotts/plyr) and may not be fixed soon. I'll keep this open to see if there are any workarounds.

**Comment by aidenlx** [comment]
use this css snippet as a temporary fix: 

```css
.media-view-player .plyr--audio {
  padding-top: 300px;
}
```
